services:

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - web
      - internal
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: library/php:8.1.0-fpm
    expose:
      - 9000
    ports:
      - 9000
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - .:/var/www/html

networks:
  web:
  internal:
    driver: bridge
